### ISSUE TITLE
generate_report - report_title not working

### ISSUE THREAD

**Issue by StuMooreCGAS** [Esri/Survey123-tools#6]
ive tried to generate a report which works but when i try to specify the report_title the generated report isnt named the same as specified:

`import datetime
from datetime import date, timedelta
nowstring = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
report = survey_by_id.generate_report(templates[6], where="objectid=10471", report_title="SUR_{0}".format(nowstring), folder_id=folder_ID)
print(report)`

returns

`<Item title:"Survey_V3_report_9c629a"`

**Comment by Zachary-Sutherby** [comment]
Hello @StuMooreCGAS, 

Please ensure the version of the ArcGIS API for Python you are using is version 1.9. Prior to the 1.9 release of the Python API the `generate_report` method was using retired syntax when submitting the request to the Survey123 Report REST API. With Python API version 1.9 and later this has been resolved. 

Thank you, 
Zach

**Comment by StuMooreCGAS** [comment]
thanks @Zachary-Sutherby i'm using the "ArcGIS Notebook Python 3 Standard - 5.0" in ArcGIS Online, i have to say i don't know what version it is

thanks

Stu

**Comment by Zachary-Sutherby** [comment]
Hello @StuMooreCGAS, 

Unfortunately the current version of the ArcGIS API for Python in ArcGIS Online is 1.8.4, please see the [Available Python libraries ](https://doc.arcgis.com/en/arcgis-online/reference/available-python-libraries.htm)ArcGIS Online documentation for reference. 

The best way to work with the 1.9 version of the ArcGIS API for Python is to upgrade the `arcgis` package in a cloned Python environment in ArcGIS Pro. Please use [this link for reference](https://community.esri.com/t5/python-questions/confusion-about-python-api-version-vs-arcgis-pro/m-p/1055209/highlight/true#M61053) regarding how to upgrade the Python API version in ArcGIS Pro.

Thank you,
Zach

**Comment by StuMooreCGAS** [comment]
thanks @Zachary-Sutherby that's great it didn't occur that it was a different version
i'll close the issue

thanks

Stu
